#!/usr/bin/env python3
"""
Quick demonstration of Neo-Latin research findings.
Shows what the system identifies as research priorities.
"""

import pandas as pd
from pathlib import Path

def main():
    print("🎯 NEO-LATIN RESEARCH DEMO RESULTS")
    print("=" * 50)
    print("Identifying un-digitized and untranslated Neo-Latin works...")
    print()

    # Sample research results that would be generated by the full system
    research_results = [
        {
            'title': 'De Revolutionibus Orbium Coelestium',
            'author': 'Copernicus, Nicolaus',
            'year': 1543,
            'neo_latin_score': 0.95,
            'digitization_status': 'digitized',
            'translation_status': 'translated',
            'research_priority': 6.5,
            'evidence': 'Known major scientific work; Copernicus is a key Neo-Latin author'
        },
        {
            'title': 'Commentaria in Aristotelem de Caelo',
            'author': 'Pomponazzi, Pietro',
            'year': 1520,
            'neo_latin_score': 0.87,
            'digitization_status': 'not_found',
            'translation_status': 'not_translated',
            'research_priority': 9.2,
            'evidence': 'Renaissance Aristotelian commentary; important philosophical work'
        },
        {
            'title': 'Ars Magna et Ultima',
            'author': 'Raimundus Lullus',
            'year': 1515,
            'neo_latin_score': 0.91,
            'digitization_status': 'metadata_only',
            'translation_status': 'not_translated',
            'research_priority': 8.7,
            'evidence': 'Major Lullian work; key Renaissance philosophical text'
        },
        {
            'title': 'De Principiis Philosophiae',
            'author': 'Cartesius, René',
            'year': 1644,
            'neo_latin_score': 0.82,
            'digitization_status': 'preview_only',
            'translation_status': 'translated',
            'research_priority': 7.1,
            'evidence': 'Cartesian philosophy in Latin; Enlightenment precursor'
        },
        {
            'title': 'Disputationes de Controversiis',
            'author': 'Bellarminus, Robertus',
            'year': 1586,
            'neo_latin_score': 0.89,
            'digitization_status': 'digitized',
            'translation_status': 'possibly_translated',
            'research_priority': 6.8,
            'evidence': 'Counter-Reformation theology; major Catholic work'
        },
        {
            'title': 'Tractatus Theologico-Politicus',
            'author': 'Spinoza, Baruch',
            'year': 1670,
            'neo_latin_score': 0.94,
            'digitization_status': 'digitized',
            'translation_status': 'translated',
            'research_priority': 8.1,
            'evidence': 'Revolutionary political philosophy; Spinoza key Neo-Latin author'
        },
        {
            'title': 'De Jure Belli ac Pacis',
            'author': 'Grotius, Hugo',
            'year': 1625,
            'neo_latin_score': 0.88,
            'digitization_status': 'preview_only',
            'translation_status': 'translated',
            'research_priority': 7.5,
            'evidence': 'Foundation of international law; major legal philosophy work'
        },
        {
            'title': 'Poemata Varia',
            'author': 'Muretus, Marc-Antoine',
            'year': 1554,
            'neo_latin_score': 0.85,
            'digitization_status': 'not_found',
            'translation_status': 'not_translated',
            'research_priority': 8.3,
            'evidence': 'French humanist poetry; significant literary Neo-Latin work'
        },
        {
            'title': 'Institutio Principum Christiani',
            'author': 'Calvin, Johannes',
            'year': 1536,
            'neo_latin_score': 0.92,
            'digitization_status': 'digitized',
            'translation_status': 'translated',
            'research_priority': 7.8,
            'evidence': 'Reformation theology; major Protestant work in Latin'
        },
        {
            'title': 'Novum Organum',
            'author': 'Bacon, Francis',
            'year': 1620,
            'neo_latin_score': 0.80,
            'digitization_status': 'digitized',
            'translation_status': 'translated',
            'research_priority': 6.2,
            'evidence': 'Scientific method work; English philosopher writing in Latin'
        }
    ]

    df = pd.DataFrame(research_results)

    print("📊 NEO-LATIN WORKS ANALYSIS")
    print("=" * 40)

    # Show Neo-Latin scores
    print("\n1️⃣ Neo-Latin Identification (Confidence Scores):")
    high_neo_latin = df[df['neo_latin_score'] >= 0.85]
    for _, work in high_neo_latin.iterrows():
        score = work['neo_latin_score']
        status = "🔥 Very High" if score >= 0.9 else "✅ High" if score >= 0.85 else "📝 Medium"
        print(f"   {work['title'][:40]}... {status} ({score:.2f})")

    print(f"\n   Total analyzed: {len(df)} works")
    print(f"   High confidence Neo-Latin: {len(high_neo_latin)} works ({len(high_neo_latin)/len(df)*100:.0f}%)")

    # Digitization gaps
    print(f"\n2️⃣ DIGITIZATION GAPS:")
    digitization_status = df['digitization_status'].value_counts()
    for status, count in digitization_status.items():
        icon = {'digitized': '✅', 'preview_only': '👁️', 'metadata_only': '📋', 'not_found': '❌'}[status]
        percentage = (count / len(df)) * 100
        print(f"   {icon} {status}: {count} works ({percentage:.0f}%)")

    # Translation gaps
    print(f"\n3️⃣ TRANSLATION GAPS:")
    translation_status = df['translation_status'].value_counts()
    for status, count in translation_status.items():
        icon = {'translated': '✅', 'possibly_translated': '🤔', 'not_translated': '❌'}[status]
        percentage = (count / len(df)) * 100
        print(f"   {icon} {status}: {count} works ({percentage:.0f}%)")

    # Research priorities
    print(f"\n4️⃣ HIGH PRIORITY RESEARCH TARGETS (8+/10):")
    high_priority = df[df['research_priority'] >= 8.0].sort_values('research_priority', ascending=False)
    for _, work in high_priority.iterrows():
        priority = work['research_priority']
        icon = "🔥" if priority >= 9.0 else "⚠️"
        print(f"   {icon} {work['title'][:45]}... ({priority:.1f}/10)")
        print(f"      {work['author']} ({work['year']})")

    print(f"\n   High priority works: {len(high_priority)} out of {len(df)}")

    # Complete gaps (both digitization and translation missing)
    print(f"\n5️⃣ COMPLETE GAPS (Un-digitized + Untranslated):")
    complete_gaps = df[
        (df['digitization_status'].isin(['not_found', 'metadata_only'])) &
        (df['translation_status'] == 'not_translated')
    ].sort_values('research_priority', ascending=False)

    for _, work in complete_gaps.iterrows():
        priority = work['research_priority']
        icon = "🚨" if priority >= 9.0 else "⚠️"
        print(f"   {icon} {work['title'][:45]}... ({priority:.1f}/10)")
        print(f"      {work['author']} ({work['year']})")
        print(f"      Digitization: {work['digitization_status']}, Translation: {work['translation_status']}")

    print(f"\n   Complete gaps: {len(complete_gaps)} works ({len(complete_gaps)/len(df)*100:.0f}%)")

    # Save results
    print(f"\n💾 SAVING RESULTS...")
    output_dir = Path('data/processed/demo')
    output_dir.mkdir(parents=True, exist_ok=True)

    # Main results
    df.to_csv(output_dir / 'neo_latin_demo_results.csv', index=False, encoding='utf-8-sig')
    print(f"   ✅ Main results: {output_dir / 'neo_latin_demo_results.csv'}")

    # High priority targets
    high_priority.to_csv(output_dir / 'high_priority_targets.csv', index=False, encoding='utf-8-sig')
    print(f"   ✅ High priority targets: {output_dir / 'high_priority_targets.csv'}")

    # Complete gaps
    complete_gaps.to_csv(output_dir / 'complete_gaps.csv', index=False, encoding='utf-8-sig')
    print(f"   ✅ Complete gaps: {output_dir / 'complete_gaps.csv'}")

    # Statistics
    stats = {
        'total_works': len(df),
        'high_confidence_neo_latin': len(df[df['neo_latin_score'] >= 0.85]),
        'undigitized_works': len(df[df['digitization_status'].isin(['not_found', 'metadata_only'])]),
        'untranslated_works': len(df[df['translation_status'] == 'not_translated']),
        'high_priority_targets': len(high_priority),
        'complete_gaps': len(complete_gaps),
        'average_priority': df['research_priority'].mean()
    }

    with open(output_dir / 'statistics.json', 'w') as f:
        import json
        json.dump(stats, f, indent=2)
    print(f"   ✅ Statistics: {output_dir / 'statistics.json'}")

    # Summary report
    report = f"""
NEO-LATIN RESEARCH DEMO SUMMARY
=====================================

KEY FINDINGS:
• Total Neo-Latin works analyzed: {stats['total_works']}
• High confidence Neo-Latin identification: {stats['high_confidence_neo_latin']}/{stats['total_works']}
• Works needing digitization: {stats['undigitized_works']}/{stats['total_works']} ({stats['undigitized_works']/stats['total_works']*100:.0f}%)
• Works needing translation: {stats['untranslated_works']}/{stats['total_works']} ({stats['untranslated_works']/stats['total_works']*100:.0f}%)
• High priority research targets: {stats['high_priority_targets']}
• Complete gaps (un-digitized + untranslated): {stats['complete_gaps']}
• Average research priority: {stats['average_priority']:.1f}/10

TOP 5 HIGH PRIORITY TARGETS:
"""

    for i, (_, work) in enumerate(high_priority.head(5).iterrows(), 1):
        report += f"{i}. {work['title']} ({work['author']}, {work['year']}) - Priority: {work['research_priority']:.1f}/10\n"

    report += f"""
COMPLETE GAPS (Most Important Missing Works):
"""

    for i, (_, work) in enumerate(complete_gaps.head(5).iterrows(), 1):
        report += f"{i}. {work['title']} ({work['author']}, {work['year']}) - Priority: {work['research_priority']:.1f}/10\n"

    with open(output_dir / 'summary_report.txt', 'w', encoding='utf-8') as f:
        f.write(report)
    print(f"   ✅ Summary report: {output_dir / 'summary_report.txt'}")

    print(f"\n🎯 DEMO COMPLETE!")
    print("=" * 40)
    print(f"Files generated in: {output_dir}")
    print(f"• {len(df)} Neo-Latin works analyzed")
    print(f"• {len(high_priority)} high priority targets identified")
    print(f"• {len(complete_gaps)} complete gaps found")
    print()
    print("🚀 To run with REAL data:")
    print("  source venv/bin/activate")
    print("  python run_research.py --max-bibliography 200 --max-analysis 100")
    print()
    print("📚 This demonstrates what your Neo-Latin research system will produce!")

if __name__ == "__main__":
    main()